### ISSUE TITLE
Mock global path

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/local_pathfinding#49]
### Purpose

Run our software without having access to the actual global path

### Description

- Subscribe to `gps` to get current position
- Publish to `global_path`
- Constant in file that defines destination latlon
- Interpolate points between current position and destination and publish to global path

### Resources

- External interface topic names and types: https://github.com/UBCSailbot/custom_interfaces/blob/main/README.md#project-wide-external-interfaces
- Example node: https://github.com/UBCSailbot/local_pathfinding/blob/main/local_pathfinding/node_navigate.py
- ROS tutorial on nodes: https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.html

**Comment by jamenkaye** [comment]
It would also be nice to allow changing the global path with a [ROS parameter](https://docs.ros.org/en/rolling/Concepts/Basic/About-Parameters.html#manipulating-parameter-values-at-runtime). The benefits of the approach would be:
- We can change the global path while the system is running (by using a separate terminal window)
- Web or Net could easily change the global path, which allows us to receive paths via the website.

Also, when you are done, please write some documentation about how to use the features you implemented on [confluence](https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1763868673/Global+Pathfinding+Design+Specification). Since the page has nothing on it right now, you can feel free to change the structure if you want :)

**Comment by jamenkaye** [comment]
![image](https://github.com/UBCSailbot/local_pathfinding/assets/71156197/3bbf0f87-a0cc-4368-aed2-7554f8477575)


- Need to make PR to custom interfaces to add a service for the green circles in the diagram
- Make two separate files; one ROS and one POST
- if you're changing mock global path to a service, need to change node_navigate.py as well
